INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '北京市', '京', 'Beijing', 'BJ', '11', '北京');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '天津市', '津', 'Tianjing', 'TJ', '12', '天津');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '河北省', '冀', 'Hebei', 'HE', '13', '石家庄');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '山西省', '晋', 'Shanxi', 'SX', '14', '太原');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '内蒙古自治区', '蒙', 'Inner Mongolia', 'IM', '15', '呼和浩特');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '辽宁省', '辽', 'Liaoning', 'LN', '21', '沈阳');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '吉林省', '吉', 'Jilin', 'JL', '22', '长春');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '黑龙江省', '黑', 'Heilongjiang', 'HL', '23', '哈尔滨');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '上海市', '沪', 'Shanghai', 'SH', '31', '上海');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '江苏省', '苏', 'Jiangsu', 'JS', '32', '南京');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '浙江省', '浙', 'Zhejiang', 'ZJ', '33', '杭州');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '安徽省', '皖', 'Anhui', 'AH', '34', '合肥');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '福建省', '闽', 'Fujian', 'FJ', '35', '福州');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '江西省', '赣', 'Jiangxi', 'JX', '36', '南昌');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '山东省', '鲁', 'Shandong', 'SD', '37', '济南');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '河南省', '豫', 'Henan', 'HA', '41', '郑州');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '湖北省', '鄂', 'Hubei', 'HB', '42', '武汉');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '湖南省', '湘', 'Hunan', 'HN', '43', '长沙');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '广东省', '粤', 'Guangdong', 'GD', '44', '广州');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '广西壮族自治区', '桂', 'Guangxi', 'GX', '45', '南宁');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '海南省', '琼', 'Hainan', 'HI', '46', '海口');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '重庆市', '渝', 'Chongqing', 'CQ', '50', '重庆');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '四川省', '川', 'Sichuan', 'SC', '51', '成都');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '贵州省', '黔', 'Guizhou', 'GZ', '52', '贵阳');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '云南省', '滇', 'Yunnan', 'YN', '53', '昆明');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '西藏自治区', '藏', 'Tibet', 'XZ', '54', '拉萨');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '陕西省', '陕', 'Shaanxi', 'SN', '61', '西安');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '甘肃省', '甘', 'Gansu', 'GS', '62', '兰州');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '青海省', '青', 'Qinghai', 'QH', '63', '西宁');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '宁夏回族自治区', '宁', 'Ningxia', 'NX', '64', '银川');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '新疆维吾尔自治区', '新', 'Xinjiang', 'XJ', '65', '乌鲁木齐');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '台湾', '台', 'Taiwan', 'TW', '71', '台北');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '香港特别行政区', '港', 'Hong Kong', 'HK', '81', '香港');
INSERT INTO province(province_id, province_name_chinese, province_abbr_chinese, province_name_english, province_abbr_english, `code`, capital) 
VALUES(LOWER(REPLACE(UUID(), '-', '')), '澳门特别行政区', '澳', 'Macao', 'MO', '82', '澳门');